bind 0.0.0.0
port 26379
protected-mode no
dir /tmp

sentinel monitor mymaster host.docker.internal 6389 2
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
sentinel resolve-hostnames yes
