bind 0.0.0.0
port 6380
protected-mode no
dir /data

replicaof redis-master 6379

appendonly yes
appendfilename appendonly.aof
appendfsync everysec

replica-announce-ip host.docker.internal
replica-announce-port 6380
